<a href="https://colab.research.google.com/github/VineethaThumalapalli/women-clothing-reviews/blob/main/women_clothing_review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#Women  Clothing Review

---



#Import Library

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns


#Import DataSet

In [2]:
df=pd.read_csv('/content/Womens Clothing E-Commerce Reviews.csv')

In [3]:
df.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Clothing ID              23486 non-null  int64 
 1   Age                      23486 non-null  int64 
 2   Title                    19676 non-null  object
 3   Review                   22641 non-null  object
 4   Rating                   23486 non-null  int64 
 5   Recommended IND          23486 non-null  int64 
 6   Positive Feedback Count  23486 non-null  int64 
 7   Division Name            23472 non-null  object
 8   Department Name          23472 non-null  object
 9   Class Name               23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [5]:
df.shape

(23486, 10)

#Missing Values 

Remove missing values in Reviews Columns with no Review Text

In [6]:
df.isna().sum()

Clothing ID                   0
Age                           0
Title                      3810
Review                      845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [7]:
df[df['Review']==""]=np.NaN 

In [8]:
df['Review'].fillna("No Review",inplace=True)

In [9]:
df.isna().sum()

Clothing ID                   0
Age                           0
Title                      3810
Review                        0
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [10]:
df['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

#Define Target (y) and Feature (X)

In [11]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended IND',
       'Positive Feedback Count', 'Division Name', 'Department Name',
       'Class Name'],
      dtype='object')

In [12]:
X=df['Review']

In [13]:
y=df['Rating']

In [14]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

#Train Test Split

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size = 0.7, stratify = y, random_state=222529)


In [17]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

#Get Feature Text Coversion to Tokens

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

In [19]:
cv=CountVectorizer(lowercase=True, analyzer='word',ngram_range=(2,3),stop_words= 'english',max_features=5000)

In [20]:
X_train = cv.fit_transform(X_train)

In [21]:
cv.get_feature_names_out()

array(['0p fit', '10 12', '10 bought', ..., 'years old', 'yes runs',
       'yoga pants'], dtype=object)

In [22]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [23]:
X_test=cv.fit_transform(X_test)

In [24]:
cv.get_feature_names_out()

array(['10 12', '10 dress', '10 fit', ..., 'years come', 'yellow color',
       'yoga pants'], dtype=object)

In [25]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

#Get Model Train

In [26]:
from sklearn.naive_bayes import MultinomialNB

In [27]:
model = MultinomialNB()

In [28]:
model.fit(X_train, y_train)

MultinomialNB()

#Get Model Prediction

In [29]:
y_pred = model.predict(X_test)

In [31]:
y_pred

array([1., 3., 1., ..., 4., 5., 1.])

#Get Probability of Each Predicted Class

In [32]:
model.predict_proba(X_test)

array([[7.78740907e-01, 9.01598864e-04, 1.79547891e-01, 4.02549886e-02,
        5.54614529e-04],
       [7.96660118e-03, 1.43416215e-02, 4.93699009e-01, 3.61307730e-01,
        1.22685038e-01],
       [7.21256206e-01, 4.03144341e-03, 2.58036072e-01, 1.25219361e-04,
        1.65510592e-02],
       ...,
       [6.73754258e-02, 2.59129933e-02, 4.51350670e-02, 5.47100378e-01,
        3.14476136e-01],
       [2.87696967e-02, 1.49205297e-02, 1.61436399e-02, 3.32553749e-01,
        6.07612384e-01],
       [3.66911303e-01, 1.38987281e-02, 3.05227635e-01, 7.53649401e-02,
        2.38597393e-01]])

#Get Model Evaluation

In [33]:
from sklearn.metrics import confusion_matrix, classification_report

In [34]:
print(confusion_matrix(y_test,y_pred))

[[  22   15   21   49  146]
 [  56   33   78   86  217]
 [ 112   70  131  150  398]
 [ 156  113  177  267  810]
 [ 375  291  399  631 2243]]


In [35]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         1.0       0.03      0.09      0.05       253
         2.0       0.06      0.07      0.07       470
         3.0       0.16      0.15      0.16       861
         4.0       0.23      0.18      0.20      1523
         5.0       0.59      0.57      0.58      3939

    accuracy                           0.38      7046
   macro avg       0.21      0.21      0.21      7046
weighted avg       0.40      0.38      0.39      7046



#Recategories Ratings as poor(0) and good(1)

In [36]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

In [37]:
df.replace({'Rating':{1:0,2:0,3:0,4:1,5:1}}, inplace=True)

In [38]:
y=df['Rating']

In [39]:
X=df['Review']

#Train Test Split

In [40]:
from sklearn.model_selection import train_test_split

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size = 0.7, stratify = y, random_state=222529)


In [43]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

#Get Feature Text Conversion to Tokens

In [44]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(lowercase=True, analyzer='word',ngram_range=(2, 3),stop_words= 'english',
                   max_features=5000)


In [45]:
X_train = cv.fit_transform(X_train)
X_test=cv.fit_transform(X_test)

#Get Model Re-Train

In [46]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

#Get Model Prediction

In [47]:
y_pred = model.predict(X_test)
y_pred.shape

(7046,)

In [48]:
y_pred

array([0., 1., 1., ..., 0., 1., 1.])

#Get Model Evaluation

In [49]:
from sklearn.metrics import confusion_matrix, classification_report

In [50]:
print(confusion_matrix(y_test,y_pred))

[[ 407 1176]
 [1097 4366]]


In [51]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.27      0.26      0.26      1583
         1.0       0.79      0.80      0.79      5463

    accuracy                           0.68      7046
   macro avg       0.53      0.53      0.53      7046
weighted avg       0.67      0.68      0.67      7046

